version: "3.7"
services:
  frontend:
    build:  # Obtain a new image from an existing one
      context: . # Get from 'Dockerfile' in same folder level
    container_name: frontend-react
    ports:
      - "80:80" # nginx (production build disabled in 'Dockerfile')
      - "3000:3000" # development server for React frontend
      - "8081:8080" # API calls backend
    volumes:
      - ./src:/app/src
